core/src/clients/git.rs, core/src/operations.rs, friendshipper/src-tauri/src/repo/operations/status.rs
I tested this by writing a lockcache file with nonsense in it.
=> fix(core): handle lockcache corruption error

core/src/clients/git.rs, core/src/operations.rs
This suppresses those git log failures when folks are on a quick submit branch.
=> fix(core): handle case of deleted remote branch in log command

birdie/src-tauri/src/repo/clone.rs, friendshipper/src-tauri/src/repo/operations/clone.rs
We weren't putting the project name in the clone parameters, so we clone the repo one level higher than we should, oops!
=> fix(core): clone to correct path

friendshipper/src/lib/components/home/ContributorLayout.svelte
This fix is optimistic, but there's some sort of state issue where the headCommit shows up without a message inconsistently, so I'm handling it here.
=> fix(friendshipper): handle nullish race condition for mq messaging

friendshipper/src/lib/components/home/ContributorLayout.svelte
Fixes this error I was seeing occasionally:
```
ContributorLayout.svelte:337  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'message')
at Array.create_default_slot_9 (ContributorLayout.svelte:337:28)
at create_slot (utils.js:165:22)
at create_dynamic_element9 (TableBody.svelte:1:46)
at create_fragment126 (TableBodyCell.svelte:10:56)
at init (Component.js:148:34)
at new TableBodyCell (TableBodyCell.svelte:7:153)
at Array.create_default_slot_4 (ContributorLayout.svelte:331:38)
at create_slot (utils.js:165:22)
at create_fragment127 (TableBodyCell.svelte:7:153)
at init (Component.js:148:34)
```
=> fix(friendshipper): null message exception in ContributorLayout

friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestCard.svelte, friendshipper/src/routes/+layout.svelte
* Fix one null member 'message' when requesting merge queue results
* Handle several uncaught exceptions
* Note that you could repro these by connnecting normally to Friendshipper and then disconnecting your internet - we still spam error messages when disconnected, but at least it doesn't take down the frontend.
=> fix(friendshipper): harden some failure cases

friendshipper/src-tauri/src/system/unreal.rs
* Suppresses popups if the local build isn't in a good state, which happens to engineers all the time.
=> fix(friendshipper): run OFPA translate commandlet as unattended

core/src/storage/entry.rs, core/src/storage/mock/mod.rs, core/src/storage/mod.rs, core/src/storage/s3/mod.rs, friendshipper/src/lib/components/home/ContributorLayout.svelte
* Handle an uncaught exception in the frontend related to null commit data
* Handle an invalid unwrap() when fetching artifacts from s3. Just return an empty list in this case to the caller and log the error.
=> fix(friendshipper): more error handling

core/src/clients/git.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs, friendshipper/src/routes/source/submit/+page.svelte
This wraps the SubmitOp's execution in a process that grabs a snapshot and tries to restore it on error. It also skips files missing from disk when storing a snapshot, as Git doesn't like it when you stash deleted files. In the future maybe we can find a way to snapshot deletes but it doesn't feel critical right now.
=> fix(core): snapshots should not include deleted files

birdie/src-tauri/src/repo/push.rs, core/src/clients/git.rs, core/src/operations.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs
Let's not even bother with real git stashes. This is more reliable it seems.
=> chore(friendshipper): store the snapshot on the filesystem

friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestCard.svelte, friendshipper/src/lib/components/playtests/PlaytestModal.svelte
- playtest card overflow adjustments on the home screen
- playtest card grid layout fixes on the playtest screen
- no more editing playtest `project` after creation - it's caused a bunch of confusion
=> fix(friendshipper): a few minor UI adjustments

friendshipper/src/routes/source/submit/+page.svelte
* After performing a quicksubmit, the message type would get reset, but the UI still showed it as selected, leading to a state mismatch with the UI, which would cause the Quick Submit button to be disabled when it looked like everything was fine.
* For the type, scope, and message fields, the message validation was bound to the input event, which is executed _before_ the bound value was actually changed, causing the message validation to be 1-off. Switching to change/keyup events ensures the input is actually completed and the bound value is updated before commit message validation runs.
=> fix(friendshipper): commit message validation bugs

birdie/src-tauri/src/repo/status.rs, core/src/clients/git.rs, core/ui/src/lib/components/repo/ModifiedFilesCard.svelte, core/ui/src/lib/types/repo.ts, friendshipper/src-tauri/src/repo/operations/diff.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs, friendshipper/src-tauri/src/repo/operations/log.rs, friendshipper/src-tauri/src/repo/operations/pull.rs, friendshipper/src-tauri/src/repo/operations/status.rs, friendshipper/src-tauri/src/state.rs
* Adds an icon for the unmerged state and a tooltip to hint that the user needs to revert the file to get back to a good state. Closes #122
* Rework upstream conflict checks to always use the upstream trunk branch. Rationale is that since if users are on a branch, they only really care about conflicting with changes that have landed in trunk, since they're in control of their own branch. This allows Unreal to know if a file has been modified in upstream trunk and appropriately warn the user.
* Disallow submitting files that have upstream conflicts - the user will wind up in a state where an engineer would need to fix up their remote branch, so it's better to catch this earlier.
=> fix(core): unmerged files icon and block submit if conflicted upstream

friendshipper/src/lib/components/playtests/PlaytestModal.svelte
Turns out disabling a form input also stops the form from passing through that key in the form data. Oops!
=> fix(friendshipper): pass through project correctly when editing playtest

birdie/src-tauri/src/repo/log.rs, core/src/tauri/command.rs, friendshipper/src-tauri/src/repo/operations/log.rs, friendshipper/src-tauri/src/repo/operations/status.rs, friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/routes/+layout.svelte
two minor enhancements here:
- our git log operation had a boolean for forcing a fetch, but it was never used, so i deleted it to avoid confusion. also, i deleted the `NoOp` operation blocking the `git log` call. this should significantly increase the performance of git log commands and reduce command queue saturation
- the window now needs to be focused for automating repo refreshes to occur, and when the window is focused, we automatically run a refresh if it's been longer than a minute since the previous refresh. the idea here is that many folks work in unreal with friendshipper minimized. while it's minimized, it's currently running StatusOp's every 30 seconds... but... so is Unreal. if you put yourself in a scenario where you're saving a file and you happen to intersect with the …
=> perf(friendshipper): decrease time spent waiting for log + status refreshes

core/src/clients/git_maintenance_runner.rs
Very minor - but these spans don't provide any value and they aren't properly being parented anyhow. the maintenance runner is the only thing that runs `git maintenance` or `git fetch` so this just clears up some log spam.
=> fix(friendshipper): remove useless maintenance spans

core/src/types/repo.rs, friendshipper/src-tauri/src/repo/operations/revert.rs
* Needed for the case where the engine is directly requesting Friendshipper to revert files.
=> fix(core): allow RevertOp to skip engine check

core/src/clients/git.rs, friendshipper/src-tauri/src/repo/operations/clone.rs, friendshipper/src-tauri/src/server.rs
GC auto was causing problems with folks fetching w/ corrupt objects. We'll let the maintenance thread care about this from now on.
=> chore(friendshipper): disable gc.auto on startup

core/src/clients/aws.rs, core/src/clients/kube.rs, core/src/types/config.rs, friendshipper/src-tauri/src/auth/router.rs, friendshipper/src-tauri/src/config/router.rs, friendshipper/src-tauri/src/state.rs, friendshipper/src/lib/components/preferences/PreferencesModal.svelte, friendshipper/src/lib/regions.ts, friendshipper/src/lib/types.ts, friendshipper/src/routes/servers/+page.svelte
This enables switching between regions for deploying playtests + servers. Enabled regions are enumerated as part of dynamic config. 
At present the default is still `us-west-2`.
=> feat(friendshipper): add support for multiple playtest regions

core/src/clients/git.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs
This deprecates the behavior where we lay down a temporary `.stash` directory. 
What's interesting is that we're actually able to ignore the `unable to unlink` error that's thrown when the editor is open. I noticed in my testing that the snapshot totally works. Git must be attempting to touch some metadata on the file that is irrelevant to us.
=> chore(friendshipper): unify snapshot behavior on submit

birdie/src-tauri/src/repo/locks.rs, birdie/src-tauri/src/repo/revert.rs, core/src/clients/git.rs, core/src/operations.rs, core/src/types/locks.rs, friendshipper/src-tauri/src/repo/operations/locks/lock.rs, friendshipper/src-tauri/src/repo/operations/revert.rs
* Now that we're pushing status updates to the engine, updating the repo status with the latest lock info ensures that it has more up-to-date locks info when sending status updates after a filewatch trigger.
* Moved the LockOp to be run in a task sequence to avoid racing with the status op
=> chore(core): update repo state with updated locks after lock op

core/src/clients/git.rs
- Adding check to prevent hundreds of git processes from spawning because the user's credentials expired. Only checking if several git-credential-manager instances are running simultaneously. Any more than 4 will prevent a git command from executing — hopefully this is high enough to prevent false positives, but low enough to prevent the issue.
=> fix(ethos): Prevent runaway process creation

Cargo.lock, Cargo.toml, birdie/src-tauri/Cargo.toml, birdie/src-tauri/src/system/update.rs, birdie/src/lib/config.ts, birdie/src/routes/+layout.svelte, core/Cargo.toml, core/src/utils/mod.rs, core/src/utils/update.rs, friendshipper/src-tauri/Cargo.toml, friendshipper/src-tauri/src/system/update.rs
Now that both Birdie and Friendshipper use the GitHub releases flow for updates, they can share logic for detecting the latest version and updating. 
Also snuck in a small fix that removes a config endpoint Birdie was calling that doesn't exist for Birdie specifically.
=> chore(birdie): unify update flow into core

core/src/clients/git.rs, friendshipper/src-tauri/src/builds/router.rs
If you drop a stash in the middle of the stack, all the indices change, duh! So in cases where we were trying to drop two stashes, we'd drop 1, then the 2nd one might go out of bounds.
=> fix(core): only drop 26th stash when there are greater than 25

core/src/clients/git.rs
This is a little bit of a shot in the dark - git seems to sometimes be parsing `--autostash` as an additional ref argument, resulting in `cannot rebase onto multiple branches`.
=> fix(core): put autostash flag at the end

birdie/src-tauri/src/command.rs, birdie/src-tauri/src/lib.rs, birdie/src-tauri/src/main.rs, birdie/src/lib/components/preferences/PreferencesModal.svelte, birdie/src/lib/config.ts, birdie/src/lib/stores.ts, birdie/src/lib/types.ts
During cutover, I did not update the core get_app_config and update_app_config to handle two config types (friendshipper config and birdie config)
Fixed so that birdie owns it's own get/update_config commands
=> fix(birdie): use birdie specific get_config + update_config

friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/home/PlaytestLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestCard.svelte, friendshipper/src/lib/types.ts, friendshipper/src/lib/utils.ts, friendshipper/src/routes/+layout.svelte, friendshipper/src/routes/playtests/+page.svelte
restarting seems like the safest way to make sure we don't make a bunch of requests after login expires.
=> chore(friendshipper): force a restart to re-prompt auth

birdie/src-tauri/src/command.rs, core/src/tauri/command.rs, friendshipper/src-tauri/src/command.rs, friendshipper/src/routes/servers/+page.svelte
Now that we throw 500s, `is_client_error` isn't enough, as that only checks 4xx.
=> fix(core): check for server errors now that we throw 500s

birdie/src-tauri/src/tools/router.rs
Tools sync was using the clone to directory instead of the git repo directory. Grabbing repo name from url and appending it to the tools_path so sync targets the right directory.
=> fix(birdie): tools sync path

core/src/operations.rs
* There have been some instances of lock paths being duplicated in the request, leading to failed lock requests. These changes ensure there are no duplicated paths in the request.
=> fix(core): dedup lock paths

birdie/src-tauri/src/main.rs, core/src/types/config.rs, core/src/utils/logging.rs, friendshipper/src-tauri/src/auth/router.rs, friendshipper/src-tauri/src/config/router.rs, friendshipper/src-tauri/src/main.rs, friendshipper/src-tauri/src/server.rs, friendshipper/src-tauri/src/state.rs
This change allows us to start the app with otel running. For Birdie, because we don't yet have an otel mechanism, this does nothing yet. For Friendshipper, we now allow caching otel config returned from dynamic config in the local app config file. So, your very first start up will not be instrumented, but provided that there is otel config in dynamic config, subsequent startups will be instrumented.
=> chore(core): make otel accessible during startup

friendshipper/src-tauri/src/repo/operations/gh/submit.rs
* If UE is not open, just submit the files, running the commandlet takes way too long
=> fix(friendshipper): disable offline OFPA translation on submit

friendshipper/src-tauri/src/builds/router.rs, friendshipper/src-tauri/src/engine/provider.rs, friendshipper/src-tauri/src/engine/unreal/provider.rs, friendshipper/src-tauri/src/repo/operations/download_dlls.rs, friendshipper/src-tauri/src/repo/operations/pull.rs, friendshipper/src-tauri/src/repo/operations/update_engine.rs
* Unreal looks for the file Engine/Restricted/NotForLicensees/Build/EpicInternal.txt when it starts up to determine if the build can contain PII such as username and commandline. This info is important for engineers when tracing the source and cause of crashes, so we'll stamp it when the engine or client gets downloaded.
=> chore(friendshipper): stamp EpicInternal.txt sentinel for PII in crash uploads

friendshipper/src-tauri/src/engine/unreal/provider.rs, friendshipper/src-tauri/src/repo/operations/pull.rs
* Ensure if any files are stashed at the beginning of the pull operation, that they are popped if something goes wrong so the user retains their files and doesn't have to manually unstash them.
* The above also fixes a bug where if the user switched back to trunk from a f11r branch with local changes, but the pull exited early due to no new changes on latest, the files would stay in the stash and not get unstashed.
* When on trunk, remove one of the status updates that was unecessary. Saves a full status update time (~4-6s).
* Avoid running DLL search when running status at the beginning of the pull operation since the final status update will fetch that info. Saves ~3s.
* When refreshing status, only push changes to the Unreal engine process if it is actually running instead of letting …
=> fix(friendshipper): misc pull operation fixes

friendshipper/src-tauri/src/main.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs
Also, disable deep link registration for mac.
=> chore(friendshipper): poll for pr mergeability in a separate thread

core/src/clients/github.rs, core/src/types/github/graphql/get_pull_requests.graphql, friendshipper/src-tauri/src/command.rs, friendshipper/src-tauri/src/repo/operations/gh/pulls.rs, friendshipper/src/routes/source/submit/+page.svelte
This switches the get_pull_requests GraphQL query to use the search API and filter for the user's PRs. This lets us show a lot more history in the Submit view.
#7700405570
=> chore(friendshipper): switch to user-specific query for PRs, show more

core/src/utils/junit.rs, friendshipper/src/lib/components/workflows/WorkflowTable.svelte, friendshipper/src/routes/+layout.svelte
* Frontend router now supports deeplinks of the form friendshipper://builds/{group}/{commit}/{workflow-name}
* The deeplink opens the builds page, the selected commit entry, and the specified workflow dialog.
* Also fixed a minor junit parsing bug where testcases can be optional within the root suite
=> chore(core): support deeplinks to builds

core/src/clients/kube.rs, core/src/types/gameserver.rs, core/src/types/playtests.rs, friendshipper/src-tauri/src/builds/router.rs, friendshipper/src-tauri/src/servers/router.rs, friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/home/PlaytestLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestCard.svelte, friendshipper/src/lib/components/playtests/PlaytestModal.svelte, friendshipper/src/lib/components/servers/ServerModal.svelte, friendshipper/src/lib/components/servers/ServerTable.svelte, friendshipper/src/lib/types.ts
This relies on some new readiness capabilities in f11r-operator.
For now, if a user attempt to sync/launch for a server that's not ready, it'll early out and prompt to try again. Also, the status dots on playtest servers will now reflect whether or not the underlying pod is ready.
=> feat(friendshipper): allow waiting for server status before launching

friendshipper/src-tauri/src/engine/mod.rs, friendshipper/src-tauri/src/engine/provider.rs, friendshipper/src-tauri/src/engine/router.rs, friendshipper/src-tauri/src/engine/unreal/ofpa.rs, friendshipper/src-tauri/src/engine/unreal/provider.rs, friendshipper/src-tauri/src/lib.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs, friendshipper/src-tauri/src/repo/operations/pull.rs, friendshipper/src-tauri/src/repo/operations/reset.rs, friendshipper/src-tauri/src/repo/operations/status.rs
* Because Unreal can go into a blocking "slow task mode" on its' main thread and not ever respond to requests we issue, expose a new handler that Unreal can ping to say when it's going into/out of a slow task. When Unreal is in a slow task, we drop all existing requests to Unreal and don't allow new ones.
=> chore(friendshipper): drop unreal requests while it's in a slow task

core/src/clients/kube.rs, core/src/types/config.rs, core/src/types/gameserver.rs, core/src/types/playtests.rs, friendshipper/src-tauri/src/repo/operations/status.rs, friendshipper/src-tauri/src/servers/router.rs, friendshipper/src/lib/components/home/PlaytestLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestModal.svelte, friendshipper/src/lib/components/servers/ServerModal.svelte, friendshipper/src/lib/gameServers.ts, friendshipper/src/lib/types.ts
* New optional field in friendshipper.yaml: playtestProfiles. Use it to specify a set of cmdline args that will be passed to the game server. If empty, a default profile (empty) is generated automatically.
* Expose selection of server arg profiles in the Playtest and Server modal UIs.
* Plumb server arguments through to kube request
=> feat(core): pipe custom cmdline args to gameserver

core/src/types/config.rs, friendshipper/src/lib/components/playtests/PlaytestModal.svelte, friendshipper/src/lib/components/servers/ServerModal.svelte
* Because we leave $repoConfig null when `repoPath` is null, we need to handle this case where we display UI for the playtest profiles. Simply not showing the profiles UI in this case is enough.
=> fix(core): playtest layout had null profiles

friendshipper/src-tauri/src/repo/operations/changeset.rs
* A previous version of friendshipper was causing changeset files to be created as folders. Users would get stuck in this state and then the write command was never able to overwrite the file with the folder. This change simply deletes the folder on load so it's able to be saved out correctly later.
=> fix(friendshipper): handle invalid changeset folder

friendshipper/src-tauri/src/command.rs, friendshipper/src-tauri/src/main.rs, friendshipper/src-tauri/src/repo/operations/mod.rs, friendshipper/src-tauri/src/repo/operations/update_engine.rs, friendshipper/src-tauri/src/repo/router.rs, friendshipper/src/lib/components/preferences/PreferencesModal.svelte, friendshipper/src/lib/repo.ts, friendshipper/src/routes/source/history/+page.svelte
* There have been several cases where people have reported broken engines after switching to a branch with a different engine and updating. This adds a mitigation where users can have a convenient button that will delete all prebuilt engine binaries and data, and redownload it.
=> feat(friendshipper): reset engine in danger zone

core/src/longtail.rs, friendshipper/src-tauri/src/repo/operations/update_engine.rs
* When retrying a download, clear the target download path in addition to the cache. Longtail seems to have trouble sometimes if there are already files there.
=> chore(core): harden longtail get_archive()

core/src/clients/git.rs, friendshipper/src-tauri/src/command.rs, friendshipper/src-tauri/src/engine/router.rs, friendshipper/src-tauri/src/main.rs, friendshipper/src-tauri/src/repo/operations/status.rs, friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/preferences/PreferencesModal.svelte, friendshipper/src/lib/engine.ts, friendshipper/src/lib/stores.ts, friendshipper/src/routes/+layout.svelte
- check that the editor is running before swapping target branches
- only look at modified files for determining upstream conflicts. this is a little spicy but ultimately the command we were using no longer detects paths accurately because your pull might be a rebase with previously applied commits.
- add some clearer error handling to the preferences modal
=> fix(core): assorted target branch swapping fixes

core/ui/src/lib/components/repo/ModifiedFilesCard.svelte, friendshipper/src-tauri/src/repo/operations/gh/auto_merge_submit.rs, friendshipper/src-tauri/src/repo/operations/gh/submit.rs, friendshipper/src/routes/+layout.svelte, friendshipper/src/routes/source/submit/+page.svelte
This speeds up some of the status calls during the submit flow and fixes a few changeset selection/refresh bugs.
=> chore(friendshipper): remove extra status calls from submit flow

friendshipper/server/Dockerfile
RustCrypto bumped MSRV to 1.85, so moving to current
=> fix(server): bump f11r-server rust version

core/src/types/builds.rs, friendshipper/src-tauri/src/builds/router.rs, friendshipper/src/lib/components/home/ContributorLayout.svelte, friendshipper/src/lib/components/home/PlaytestLayout.svelte, friendshipper/src/lib/components/playtests/PlaytestCard.svelte, friendshipper/src/lib/components/servers/ServerModal.svelte, friendshipper/src/lib/components/servers/ServerTable.svelte, friendshipper/src/lib/stores.ts, friendshipper/src/lib/types.ts, friendshipper/src/routes/+layout.svelte
2 things:
* Fixed a bug with Friendshipper not detecting you have the client already synced for a build until you click sync at least once
* Added a new button that will launch the client without a server to the playtest card
=> feat(friendshipper): new button to launch without server for playtests
