- birdie/src/routes/source/submit/+page.svelte
- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
- friendshipper/src/routes/source/submit/+page.svelte
closes #33 
https://github.com/believer-oss/ethos/assets/12792264/d5eab9fe-b11a-4fe0-ac33-fde6318d2f40
> chore(core): add folder open to modified files view

- core/src/clients/kube.rs
- core/src/lib.rs
- core/src/types/gameserver.rs
- core/ui/package.json
- core/ui/src/lib/components/repo/CommitTable.svelte
- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
- core/ui/yarn.lock
- friendshipper/package.json
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/servers/router.rs
- friendshipper/src/lib/components/preferences/PreferencesModal.svelte
- friendshipper/src/lib/components/servers/ServerModal.svelte
- friendshipper/src/lib/components/servers/ServerTable.svelte
- friendshipper/src/lib/components/workflows/WorkflowTable.svelte
- friendshipper/src/lib/gameServers.ts
- friendshipper/src/routes/+layout.svelte
- friendshipper/src/routes/+page.svelte
- friendshipper/src/routes/builds/+page.svelte
- friendshipper/src/routes/ludos/objects/+page.svelte
- friendshipper/src/routes/servers/+page.svelte
- friendshipper/src/routes/source/diagnostics/+page.svelte
- friendshipper/src/routes/source/history/+page.svelte
- friendshipper/src/routes/source/locks/+page.svelte
- friendshipper/src/routes/source/submit/+page.svelte
- friendshipper/src/routes/system/logs/+page.svelte
- friendshipper/yarn.lock
> feat(friendshipper): vendor ServerTable

- friendshipper/src-tauri/src/system/update.rs
the self-updater pulls info from public github, so it should not need a PAT.
> fix(friendshipper): update without PAT

- birdie/src-tauri/src/repo/revert.rs
- friendshipper/src-tauri/src/repo/operations/revert.rs
Reverting > 50-ish files explodes because Windows has a limit on how long a single command can be
> fix(core): revert should batch its arguments

- friendshipper/src-tauri/src/system/update.rs
I missed the octocrab token usage in the last PR. :face_holding_back_tears:
> fix(friendshipper): use PAT for octocrab in update

- core/src/clients/git.rs
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/main.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
- friendshipper/src-tauri/src/repo/operations/mod.rs
- friendshipper/src-tauri/src/repo/operations/reset.rs
- friendshipper/src-tauri/src/repo/router.rs
- friendshipper/src/lib/components/preferences/PreferencesModal.svelte
- friendshipper/src/lib/repo.ts
Also attempts to restore previous state when git submit fails.
> feat(friendshipper): add danger zone reset to main

- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
* Leaving this branch around can be confusing to some people, so just clean it up after the merge.
> fix(friendshipper): cleanup worktree branch

- core/src/clients/git.rs
- core/src/operations.rs
- core/src/types/config.rs
* The batch lock operations weren't updating the readonly flag settings on files post lock/unlock according to the lfs.setlockablereadonly config value.
> fix(core): respect lfs.setlockablereadonly setting

- birdie/src-tauri/src/command.rs
- birdie/src-tauri/src/lib.rs
- birdie/src-tauri/src/main.rs
- birdie/src-tauri/src/tools/mod.rs
- birdie/src-tauri/src/tools/router.rs
- birdie/src/lib/components/preferences/PreferencesModal.svelte
- birdie/src/lib/tools.ts
- birdie/src/lib/types.ts
- birdie/src/routes/source/history/+page.svelte
- core/src/types/config.rs
This is just the functional code and Preferences page. I'm not including the button to run the clone/sync until I return so that it doesn't mis-lead artists.
> mkinzelman tools repo clone and sync from birdie

- core/src/clients/git.rs
* If a git config variable is unset when you --get it, the process exits with error code 1, but this is a benign error that can be swallowed, and the caller can emit an error if the output isn't what they expected.
> fix(core): silence git config --get error spam

- friendshipper/src/routes/system/logs/+page.svelte
- Timestamps in System Logs now have formatting based on the System Locale.
> chore(friendshipper): Timestamp in System > Logs

- friendshipper/src-tauri/src/repo/operations/revert.rs
* The LFS post-checkout hook updates the files given, but then, if the lfs.setlockablereadonly config is true, which is on by default, it takes the hook opportunity to check all files in the repo to ensure they are properly conforming to the readonly flag. However, this process is very slow for repos with large numbers of LFS files (such as Unreal projects!). One test showed to check ~30k files took ~8s. This behavior compounds with the previous chunking behavior we were doing where reverting large amounts of files would split them up into chunks of 50 to avoid commandline limits. So reverting ~500 files (common when working with Unreal OFPA files) would be bloated by overhead of ~8s for every chunk, making the whole revert operation take minutes.
* These changes try to use the …
> perf(friendshipper): revert use pathspec-from-file

- friendshipper/src/lib/components/home/ContributorLayout.svelte
- friendshipper/src/lib/components/playtests/PlaytestCard.svelte
also cleans up some alignment on the playtest card
> chore(friendshipper): add open editor button to contrib view

- core/src/clients/git.rs
- core/src/clients/git_maintenance_runner.rs
- core/src/clients/mod.rs
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
- friendshipper/src-tauri/src/repo/operations/pull.rs
- friendshipper/src-tauri/src/repo/operations/status.rs
- friendshipper/src-tauri/src/server.rs
- friendshipper/src/lib/components/oobe/WelcomeModal.svelte
- friendshipper/src/lib/repo.ts
- friendshipper/src/routes/+layout.svelte
This makes all fetching on demand by polling the github API for the latest commit on the trunk.
> feat(friendshipper): move fetching and maintenance tasks into background

- birdie/src/lib/types.ts
- birdie/src/routes/source/submit/+page.svelte
- core/src/operations.rs
- friendshipper/src/lib/types.ts
- friendshipper/src/routes/source/submit/+page.svelte
* Forgot to add the skipEngineCheck to the frontend RevertFilesRequest in Birdie and Friendshipper.
> fix(core): busted revert in frontend

- birdie/src/routes/+layout.svelte
- friendshipper/src/routes/+layout.svelte
- Birdie and Friendshipper titles are no longer selectable. Fixes Window dragging in the title bar.
> fix(birdie/friendshipper): Title being selectable

- birdie/src/lib/components/oobe/WelcomeModal.svelte
- friendshipper/src/lib/components/oobe/WelcomeModal.svelte
not sure if core is the right scope? it's not technically in the core package but it is a fix to both friendshipper and birdie
> fix(core): remove spaces on some setup inputs

- friendshipper/src-tauri/src/repo/operations/pull.rs
When switching back from a quicksubmit branch, we save a stash. The way this is currently ordered, it's:
1. save stash
2. save snapshot
3. stash pop
Which results in 1. anything that's stashed not going into the snapshot, and 2. a snapshot which has either nothing or only added new files.
This fix swaps it to:
1. save snapshot
2. save stash
3. stash pop
That way we're always popping the stash we just saved.
> fix(friendshipper): take snapshot before attempting to stash during pull

- friendshipper/src/lib/components/oobe/WelcomeModal.svelte
- friendshipper/src/routes/+layout.svelte
* Missed a couple spots last time when disabling this. It will eventually turn into an opt-in but we don't have UI for it yet.
> chore(friendshipper): disable OFPA commandlet

- birdie/src-tauri/src/config/router.rs
- birdie/src-tauri/src/lib.rs
- birdie/src-tauri/src/repo/locks.rs
- birdie/src-tauri/src/repo/pull.rs
- birdie/src-tauri/src/repo/revert.rs
- birdie/src-tauri/src/server.rs
- birdie/src-tauri/src/state.rs
- birdie/src-tauri/src/system/update.rs
- birdie/src-tauri/src/tools/router.rs
- birdie/src-tauri/src/types/config.rs
- birdie/src-tauri/src/types/mod.rs
- birdie/src/lib/stores.ts
- birdie/src/lib/types.ts
- core/src/types/config.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
- friendshipper/src-tauri/src/repo/operations/locks/lock.rs
- friendshipper/src-tauri/src/repo/operations/revert.rs
will move the friendshipper config.yaml out of core in a seperate PR
> refactor(birdie): pull birdie config.yaml out of core

- birdie/src-tauri/src/repo/locks.rs
- birdie/src/routes/source/submit/+page.svelte
- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
> feat(birdie): lock all button

- birdie/src-tauri/src/main.rs
- birdie/src-tauri/src/system/mod.rs
- birdie/src-tauri/src/system/router.rs
- birdie/src-tauri/src/system/terminal.rs
- birdie/src/lib/components/preferences/PreferencesModal.svelte
- birdie/src/lib/system.ts
- friendshipper/src-tauri/src/system/terminal.rs
- friendshipper/src/lib/components/preferences/PreferencesModal.svelte
> feat(birdie): open terminal buttons

- core/src/clients/git.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
* git stash push by default clears the working tree. We were using --keep-index to retain changes to it, but it turns out that the way it's implemented winds up modifying the files anyway. If Unreal is open, and happens to be holding onto a handle for some files that are getting stashed, the command will fail, leaving the repo in a bad state. Using the git stash create/store commands avoids this behavior, leading to a stash commit being created and stored in the stash list as desired, without touching the working tree at all. It's worth noting that the implementation of the create seems to not respect --include-untracked, but it doesn't matter because we're adding all the stashed files to the index anyway.
* Removed --include-untracked since we're already adding files in both the "stash …
> fix(core): snapshots leaving the worktree in a bad state

- friendshipper/docs/sourcecontrol.md
- friendshipper/src/lib/components/playtests/PlaytestModal.svelte
> fix(friendshipper): allow 25 playtest groups

- core/src/clients/git.rs
just a little instrumentation cleanup
> fix(core): remove extra instrumentation of git error

- birdie/src/routes/+page.svelte
> feat(birdie): add sync and tools button to home page

- core/src/types/config.rs
- friendshipper/src/lib/components/servers/ServerTable.svelte
- friendshipper/src/lib/types.ts
Dynamic config is best here because it allows the config to be accessible to all users, not just users who have the game repo cloned.
> fix(friendshipper): move mobile scheme into dynamic config

- birdie/src-tauri/src/command.rs
- birdie/src-tauri/src/repo/lfs.rs
- birdie/src/lib/repo.ts
- birdie/src/routes/+page.svelte
> feat(birdie): option to include/skip WIP folders on dl

- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
the changesets weren't getting updates like locked status being changed, oops!
> fix(core): update data in ModifiedFile on refresh

- friendshipper/src/routes/source/submit/+page.svelte
> chore(friendshipper): add commits button group to submit view

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/auth/sso.rs
- core/src/clients/aws.rs
- friendshipper/src-tauri/src/lib.rs
- friendshipper/src-tauri/src/storage/mod.rs
- friendshipper/src-tauri/src/storage/router.rs
- friendshipper/src/lib/components/playtests/PlaytestCard.svelte
- friendshipper/src/routes/+layout.svelte
this gives friendshipper an entrypoint for storing and retrieving repo-related files via s3
> feat(friendshipper): introduce storage API via s3

- friendshipper/src-tauri/Cargo.toml
- friendshipper/src-tauri/tauri.conf.json
- friendshipper/src/lib/components/workflows/WorkflowLogsModal.svelte
* Added a button to the build logs page to copy the currently-displayed log to the clipboard.
> feat(friendshipper): add "copy logs to clipboard" button

- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
- core/ui/src/lib/types/repo.ts
> feat(core): move changelist rename, select all, delete

- birdie/src-tauri/src/command.rs
- birdie/src-tauri/src/main.rs
- birdie/src-tauri/src/repo/file.rs
- birdie/src-tauri/src/repo/mod.rs
- birdie/src-tauri/src/repo/router.rs
- birdie/src/lib/components/files/FileTree.svelte
- birdie/src/lib/components/files/TreeNode.svelte
- birdie/src/lib/repo.ts
- birdie/src/lib/stores.ts
- birdie/src/lib/types.ts
- birdie/src/routes/+page.svelte
> feat(birdie): file tree view for asset explorer

- friendshipper/src-tauri/src/server.rs
> feat(friendshipper): increase http buffer size in git config

- core/ui/src/lib/components/repo/CommitTable.svelte
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/main.rs
- friendshipper/src-tauri/src/repo/operations/mod.rs
- friendshipper/src-tauri/src/repo/operations/reset.rs
- friendshipper/src-tauri/src/repo/router.rs
- friendshipper/src/lib/repo.ts
- friendshipper/src/routes/source/history/+page.svelte
this allows users to reset repo to a previous commit and keep their local changes
> feat(friendshipper): git reset --keep <sha>

- birdie/src/routes/+page.svelte
> fix(birdie): fix show in explorer for file tree view

- Cargo.lock
- core/Cargo.toml
- core/src/clients/git.rs
- core/src/types/builds.rs
- friendshipper/src-tauri/Cargo.toml
- friendshipper/src-tauri/src/builds/router.rs
- friendshipper/src/lib/components/home/ContributorLayout.svelte
- friendshipper/src/lib/components/home/PlaytestLayout.svelte
- friendshipper/src/lib/components/playtests/PlaytestCard.svelte
- friendshipper/src/lib/components/servers/ServerModal.svelte
- friendshipper/src/lib/components/servers/ServerTable.svelte
- friendshipper/src/lib/types.ts
> fix(friendshipper): assortment of playtest/snapshot fixes

- core/src/clients/git.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
This changes the submit flow to only set up the worktree when we're already on an f11r branch. After reviewing some trace data, the worktree bits seem to add quite a bit of time to the submit process, especially the `git rebase origin/main`. It may be that something is malfunctioning in that bit, but for now it felt reasonable to skip it when doing a submit directly off of main.
Also, I stopped sending all git logs to the frontend, as they've just gotten a bit too noisy. I've replaced it with a printout of which command is being run (truncated beyond 8 arguments to avoid blasting hundreds of file paths to the UI).
> chore(friendshipper): only set up worktree when necessary

- birdie/src-tauri/src/repo/status.rs
- core/src/types/repo.rs
- friendshipper/src-tauri/src/repo/operations/status.rs
* adding local commit_head info, commits_ahead and commits_behind trunk
> chore(core): more status telemetry

- Cargo.lock
- birdie/src-tauri/Cargo.toml
- birdie/src-tauri/src/main.rs
- birdie/src-tauri/src/repo/diagnostics/rebase.rs
- birdie/src-tauri/src/repo/file.rs
- birdie/src-tauri/src/repo/lfs.rs
- birdie/src-tauri/src/repo/locks.rs
- birdie/src-tauri/src/repo/pull.rs
- birdie/src-tauri/src/repo/push.rs
- birdie/src-tauri/src/repo/revert.rs
- birdie/src-tauri/src/repo/show.rs
- birdie/src-tauri/src/server.rs
- birdie/src-tauri/src/types/config.rs
- core/src/clients/git.rs
Also instrumented a bunch of stuff.
> feat(birdie): hook up otel via repo-level config file

- friendshipper/src-tauri/src/server.rs
When instrumenting server startup time, we accidentally moved the watcher into a helper function for easy instrumentation. Unfortunately this resulted in it falling out of scope. 😅
> fix(friendshipper): keep file watcher in scope

- core/src/clients/git.rs
- core/src/clients/git_maintenance_runner.rs
- friendshipper/src-tauri/src/repo/operations/update_engine.rs
- friendshipper/src-tauri/src/repo/project/router.rs
- friendshipper/src-tauri/src/server.rs
- friendshipper/src-tauri/tauri.conf.json
- friendshipper/src/routes/+layout.svelte
Also runs gc and reflog expire on startup
> chore(friendshipper): show git cmds running during startup

- core/src/clients/argo.rs
- core/src/clients/kube.rs
- core/src/types/argo/workflow.rs
- core/src/utils/junit.rs
- friendshipper/src-tauri/src/builds/router.rs
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/main.rs
- friendshipper/src/lib/builds.ts
- friendshipper/src/lib/components/servers/ServerTable.svelte
- friendshipper/src/lib/components/workflows/WorkflowLogsModal.svelte
- friendshipper/src/lib/components/workflows/junit/JunitDisplay.svelte
- friendshipper/src/lib/components/workflows/junit/JunitTestCase.svelte
- friendshipper/src/lib/components/workflows/junit/JunitTestSuite.svelte
- friendshipper/src/lib/types.ts
> feat(friendshipper): display junit output for builds

- core/src/clients/kube.rs
- core/src/types/playtests.rs
- friendshipper/src-tauri/src/playtests/router.rs
- friendshipper/src/lib/components/playtests/PlaytestModal.svelte
- friendshipper/src/lib/playtests.ts
> feat(friendshipper): add option to auto cleanup playtests

- birdie/src-tauri/src/server.rs
- birdie/src/routes/+layout.svelte
- core/src/clients/git.rs
- friendshipper/src-tauri/src/repo/operations/status.rs
- friendshipper/src-tauri/src/server.rs
> chore(core): update maintenance tasks for birdie and friendshipper

- friendshipper/src/routes/playtests/+page.svelte
> chore(friendshipper): add playtest auto refresh and refresh button

- friendshipper/src/routes/servers/+page.svelte
> chore(friendshipper): add open folder button to servers page

- friendshipper/src-tauri/src/engine/unreal/provider.rs
> chore(friendshipper): instrument is_editor_process_running

- birdie/src-tauri/src/repo/file.rs
- birdie/src/lib/components/files/FileTree.svelte
- birdie/src/routes/+page.svelte
Also:
- Disabled some file metadata stuff that we aren't really using yet
- Rebalanced the UI a bit to allow more space for commits
> chore(birdie): show commit history for folders

- core/src/types/config.rs
- friendshipper/src-tauri/src/engine/mod.rs
- friendshipper/src-tauri/src/engine/provider.rs
- friendshipper/src-tauri/src/engine/unreal/provider.rs
- friendshipper/src-tauri/src/repo/project/router.rs
- friendshipper/src/lib/components/preferences/PreferencesModal.svelte
- friendshipper/src/lib/types.ts
* https://believer.atlassian.net/browse/FEL-3853: [Friendshipper] Provide functionality to launch multiple Unreal Editors (with optional checkbox)
* New user config setting defaults to off, which can be changed in Preferences
> feat(friendshipper): allow opening multiple editors

- core/src/clients/git.rs
This prevents multiple fetch operations from running concurrently, which can trigger an error when they are both modifying the same ref.
An implementation with `Arc<Mutex<()>>` or `Arc<AtomicBool>` was considered, but the overhead for this case seems negligible. Could go either way...
I believe there's a strong case that the entire `Git::run_and_collect_output_internal` should instead be single-threaded, but wanted to discuss any potential pitfalls first. Are there any cases where we benefit from multiple concurrent git operations?
> fix(core): prevent concurrent fetch operations

- .github/workflows/rust.yml
- birdie/src-tauri/src/config/router.rs
- birdie/src-tauri/src/repo/clone.rs
- core/src/operations.rs
- friendshipper/src-tauri/src/config/router.rs
- friendshipper/src-tauri/src/repo/operations/clone.rs
locks_ours doesn't include locks other people own, but allow the file to be dropped if we're forcing
> fix(core): releasing other people's locks

- core/src/longtail.rs
- core/src/storage/entry.rs
- core/ui/src/lib/components/repo/ModifiedFilesCard.svelte
- friendshipper/src/lib/components/preferences/PreferencesModal.svelte
- friendshipper/src/routes/source/submit/+page.svelte
When taking on updated to modified files in the ModifiedFilesCard component, we were ignoring any updates to the metadata in the files, and only removing files no longer in the modified files array.
> fix(core): make sure file meta updates in modified files card

- friendshipper/src-tauri/src/engine/unreal/provider.rs
* Handle relative paths to uprojects
* Handle multiple slashes in a given path (e.g. my\\cool\\\path is valid on windows)
> fix(friendshipper): incorrect detection of running Unreal editor

- friendshipper/src-tauri/src/repo/operations/file_history.rs
- File History now gets all previous revision history async instead of serially
> perf(friendshipper): File History performance

- friendshipper/src/routes/source/submit/+page.svelte
* UnrealVersionSelector has behavior that likes to modify the uproject file's EngineAssociation with whatever it's using to open the editor. This is always undesired, and often leaves users in a weird state where the wrong engine is used to open the project. This change brings more visibility to when that happens so content creators can self-serve a bit more.
> chore(friendshipper): prompt to revert uproject for content creators

- friendshipper/src-tauri/src/repo/operations/status.rs
- friendshipper/src/routes/system/logs/+page.svelte
also set default log levels to warn/error.
> fix(friendshipper): ensure upstream branch exists before checking

- friendshipper/src-tauri/src/repo/operations/gh/auto_merge_submit.rs
- friendshipper/src-tauri/src/repo/operations/gh/submit.rs
- friendshipper/src-tauri/src/repo/operations/status.rs
- also clear out the worktree on a stacked submit
> chore(friendshipper): reorganize modified files check

- friendshipper/src-tauri/src/builds/router.rs
- friendshipper/src/lib/components/workflows/WorkflowTable.svelte
- friendshipper/src/lib/types.ts
> feat(friendshipper): add branch name to builds page

- core/src/clients/aws.rs
- friendshipper/src-tauri/src/server.rs
Previously we would read the `dynamic-config.json` file only at startup, but now we refresh it on a regular basis. This moves the dynamic-config override logic to the refresh.
> fix: move dynamicconfig override to account for code changes

- core/src/clients/argo.rs
- core/src/clients/kube.rs
- friendshipper/src-tauri/src/builds/router.rs
- friendshipper/src-tauri/src/command.rs
- friendshipper/src-tauri/src/main.rs
- friendshipper/src/lib/builds.ts
- friendshipper/src/lib/components/workflows/WorkflowLogsModal.svelte
- friendshipper/src/lib/components/workflows/WorkflowTable.svelte
- friendshipper/src/lib/types.ts
Sorry for the whitespace change.
> feat(friendshipper): lazy-load workflow status.nodes when pulling logs
